# Generated by Django 4.2.3 on 2023-07-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('isbn', models.CharField(max_length=12)),
                ('janr', models.CharField(max_length=120)),
                ('narxi', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
